// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_objects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFileObject = `-- name: CreateFileObject :one
INSERT INTO file_objects (
    id,
    filename,
    content_type,
    size_bytes,
    checksum_sha256,
    storage_backend,
    storage_bucket,
    storage_object_key,
    storage_version_id,
    storage_etag,
    status,
    created_by_service,
    request_id,
    created_at,
    updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15
)
RETURNING
    id,
    filename,
    content_type,
    size_bytes,
    checksum_sha256,
    storage_backend,
    storage_bucket,
    storage_object_key,
    storage_version_id,
    storage_etag,
    status,
    created_by_service,
    request_id,
    created_at,
    updated_at,
    deleted_at,
    delete_requested_at,
    purged_at,
    last_error_code,
    last_error_message
`

type CreateFileObjectParams struct {
	ID               string
	Filename         string
	ContentType      string
	SizeBytes        int64
	ChecksumSha256   pgtype.Text
	StorageBackend   string
	StorageBucket    pgtype.Text
	StorageObjectKey string
	StorageVersionID pgtype.Text
	StorageEtag      pgtype.Text
	Status           string
	CreatedByService pgtype.Text
	RequestID        pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateFileObject(ctx context.Context, arg CreateFileObjectParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, createFileObject,
		arg.ID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.StorageBackend,
		arg.StorageBucket,
		arg.StorageObjectKey,
		arg.StorageVersionID,
		arg.StorageEtag,
		arg.Status,
		arg.CreatedByService,
		arg.RequestID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageBackend,
		&i.StorageBucket,
		&i.StorageObjectKey,
		&i.StorageVersionID,
		&i.StorageEtag,
		&i.Status,
		&i.CreatedByService,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeleteRequestedAt,
		&i.PurgedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const getFileObject = `-- name: GetFileObject :one
SELECT
    id,
    filename,
    content_type,
    size_bytes,
    checksum_sha256,
    storage_backend,
    storage_bucket,
    storage_object_key,
    storage_version_id,
    storage_etag,
    status,
    created_by_service,
    request_id,
    created_at,
    updated_at,
    deleted_at,
    delete_requested_at,
    purged_at,
    last_error_code,
    last_error_message
FROM file_objects
WHERE id = $1
  AND deleted_at IS NULL
  AND status = 'available'
`

func (q *Queries) GetFileObject(ctx context.Context, id string) (FileObject, error) {
	row := q.db.QueryRow(ctx, getFileObject, id)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageBackend,
		&i.StorageBucket,
		&i.StorageObjectKey,
		&i.StorageVersionID,
		&i.StorageEtag,
		&i.Status,
		&i.CreatedByService,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeleteRequestedAt,
		&i.PurgedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const markFileDeleteRequested = `-- name: MarkFileDeleteRequested :one
UPDATE file_objects
SET status = CASE WHEN status = 'purged' THEN status ELSE 'delete_requested' END,
    deleted_at = COALESCE(deleted_at, $2),
    delete_requested_at = COALESCE(delete_requested_at, $2),
    updated_at = $2
WHERE id = $1
RETURNING
    id,
    filename,
    content_type,
    size_bytes,
    checksum_sha256,
    storage_backend,
    storage_bucket,
    storage_object_key,
    storage_version_id,
    storage_etag,
    status,
    created_by_service,
    request_id,
    created_at,
    updated_at,
    deleted_at,
    delete_requested_at,
    purged_at,
    last_error_code,
    last_error_message
`

type MarkFileDeleteRequestedParams struct {
	ID        string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) MarkFileDeleteRequested(ctx context.Context, arg MarkFileDeleteRequestedParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, markFileDeleteRequested, arg.ID, arg.UpdatedAt)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageBackend,
		&i.StorageBucket,
		&i.StorageObjectKey,
		&i.StorageVersionID,
		&i.StorageEtag,
		&i.Status,
		&i.CreatedByService,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeleteRequestedAt,
		&i.PurgedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const markFilePurgeFailed = `-- name: MarkFilePurgeFailed :one
UPDATE file_objects
SET status = 'failed',
    last_error_code = $2,
    last_error_message = $3,
    updated_at = $4
WHERE id = $1
RETURNING
    id,
    filename,
    content_type,
    size_bytes,
    checksum_sha256,
    storage_backend,
    storage_bucket,
    storage_object_key,
    storage_version_id,
    storage_etag,
    status,
    created_by_service,
    request_id,
    created_at,
    updated_at,
    deleted_at,
    delete_requested_at,
    purged_at,
    last_error_code,
    last_error_message
`

type MarkFilePurgeFailedParams struct {
	ID               string
	LastErrorCode    pgtype.Text
	LastErrorMessage pgtype.Text
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) MarkFilePurgeFailed(ctx context.Context, arg MarkFilePurgeFailedParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, markFilePurgeFailed,
		arg.ID,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.UpdatedAt,
	)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageBackend,
		&i.StorageBucket,
		&i.StorageObjectKey,
		&i.StorageVersionID,
		&i.StorageEtag,
		&i.Status,
		&i.CreatedByService,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeleteRequestedAt,
		&i.PurgedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const markFilePurged = `-- name: MarkFilePurged :one
UPDATE file_objects
SET status = 'purged',
    purged_at = $2,
    last_error_code = NULL,
    last_error_message = NULL,
    updated_at = $2
WHERE id = $1
RETURNING
    id,
    filename,
    content_type,
    size_bytes,
    checksum_sha256,
    storage_backend,
    storage_bucket,
    storage_object_key,
    storage_version_id,
    storage_etag,
    status,
    created_by_service,
    request_id,
    created_at,
    updated_at,
    deleted_at,
    delete_requested_at,
    purged_at,
    last_error_code,
    last_error_message
`

type MarkFilePurgedParams struct {
	ID       string
	PurgedAt pgtype.Timestamptz
}

func (q *Queries) MarkFilePurged(ctx context.Context, arg MarkFilePurgedParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, markFilePurged, arg.ID, arg.PurgedAt)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageBackend,
		&i.StorageBucket,
		&i.StorageObjectKey,
		&i.StorageVersionID,
		&i.StorageEtag,
		&i.Status,
		&i.CreatedByService,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeleteRequestedAt,
		&i.PurgedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const markFilePurging = `-- name: MarkFilePurging :one
UPDATE file_objects
SET status = CASE WHEN status = 'purged' THEN status ELSE 'purging' END,
    updated_at = $2
WHERE id = $1
RETURNING
    id,
    filename,
    content_type,
    size_bytes,
    checksum_sha256,
    storage_backend,
    storage_bucket,
    storage_object_key,
    storage_version_id,
    storage_etag,
    status,
    created_by_service,
    request_id,
    created_at,
    updated_at,
    deleted_at,
    delete_requested_at,
    purged_at,
    last_error_code,
    last_error_message
`

type MarkFilePurgingParams struct {
	ID        string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) MarkFilePurging(ctx context.Context, arg MarkFilePurgingParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, markFilePurging, arg.ID, arg.UpdatedAt)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageBackend,
		&i.StorageBucket,
		&i.StorageObjectKey,
		&i.StorageVersionID,
		&i.StorageEtag,
		&i.Status,
		&i.CreatedByService,
		&i.RequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeleteRequestedAt,
		&i.PurgedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}
