// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FileObject struct {
	ID                string
	Filename          string
	ContentType       string
	SizeBytes         int64
	ChecksumSha256    pgtype.Text
	StorageBackend    string
	StorageBucket     pgtype.Text
	StorageObjectKey  string
	StorageVersionID  pgtype.Text
	StorageEtag       pgtype.Text
	Status            string
	CreatedByService  pgtype.Text
	RequestID         pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	DeleteRequestedAt pgtype.Timestamptz
	PurgedAt          pgtype.Timestamptz
	LastErrorCode     pgtype.Text
	LastErrorMessage  pgtype.Text
}
